execute positioned ~-1 ~-1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~-1 ~0 ~-1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~-1 ~0 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~-1 ~0 ~1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~-1 ~1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~-1 ~-1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~-1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~-1 ~1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~0 ~-1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~0 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~0 ~1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~1 ~-1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~0 ~1 ~1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~1 ~-1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~1 ~0 ~-1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~1 ~0 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~1 ~0 ~1 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
execute positioned ~1 ~1 ~0 unless block ~ ~ ~ minecraft:bedrock run setblock ~ ~ ~ air replace
